behaviours:
  - HappyPath
  - ConstraintHeavyQueries
  - AmbiguousQueries
  - MultiTurnConversations
  - UserCorrections
  - AdversarialTrapQueries
  - ImpatientUser
  - LowContext
  - OverSpecified
  - EmotionallyCharged
  - NonNativeSpeaker
