workflows:
  - ProductDiscovery
  - ProductAvailability
  - StoreAvailability
  - PriceMatch
  - PromotionsCoupons
  - CheckoutPayments
  - ReturnsExchanges
  - OrderPickup
  - DeliveryScheduling
  - GiftCards
  - LoyaltyRewards
  - WarrantySupport
